[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "https://online-poll-backend.onrender.com/:splat"
  status = 200
  force = true

[headers]
  for = "/api/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://your-netlify-site.netlify.app"
    Access-Control-Allow-Credentials = "true"